// Code generated by configexport.
package sxls

type Title struct {
	Id               int32   // ID
	Name             int32   // 称号名称
	Level            int32   // 品质
	TimeType         int32   // 限时类型
	TimeLimit        int64   // 时限
	IsShow           bool    // 是否展示
	FilterType       int32   // 筛选类型
	TaskID           int32   // 解锁任务
	IsUnlock         bool    // 是否直接解锁
	ItemId           int32   // 对应道具
	AssetPathStatic  string  // 资源来源静态
	AssetPathDynamic string  // 资源来源动态
	TestStruct       Vector3 // 测试结构体
}

type Award struct {
	ID  int32 // 道具id
	Num int64 // 道具数量
}

type Vector2 struct {
	X float64 // x坐标
	Y float64 // y坐标
}

type Vector3 struct {
	X float64 // x坐标
	Y float64 // y坐标
	Z float64 // z坐标
}

type Vector4 struct {
	X float64 // x坐标
	Y float64 // y坐标
	Z float64 // z坐标
	W float64 // W坐标
}

type Color struct {
	R float64 // 红通道
	G float64 // 绿通道
	B float64 // 蓝通道
	A float64 // 透明通道
}

type Color32 struct {
	R int8 // 红通道
	G int8 // 绿通道
	B int8 // 蓝通道
	A int8 // 透明通道
}

type Award1 struct {
	ID  int32 // 道具id
	Num int32 // 道具数量
}

type Float3 struct {
	F1 float64 // 数值参数
	F2 float64 // 数值参数
	F3 float64 // 数值参数
}

type PetPath struct {
	Typ    int32   // 寻路类型
	Weight int32   // 权重
	Arg    []int32 // 参数
}

type Param1 struct {
	P1 string // 数值参数
	P2 string // 数值参数
}

type Circular struct {
	X int32 // x坐标
	Y int32 // y坐标
	Z int32 // z坐标
	R int32 // 半径
}

type IntList2 struct {
	Int int32   // 参数1
	Arg []int32 // 参数
}

type IntList1 struct {
	Int1 int32 // 参数1
	Int2 int32 // 参数2
}

type IntList3 struct {
	Int1 int32 // 参数1
	Int2 int32 // 参数2
	Int3 int32 // 参数3
}

type Condition struct {
	Cmp  string      // 比较类型
	Typ  string      // 条件类型
	ID   int32       // 参数1
	Val  int32       // 值1
	Args []Condition // 参数
}

type Award2 struct {
	Atlas string // 道具图标名称
	Icon  string // 道具图标名称
	Num   int32  // 道具数量
}

type FxPath struct {
	Id   int32  // 动作ID
	Path string // 特效路径
	Time int32  // 特效时间
}

type RawConfig struct {
	Title []*Title
}

var AllValues = map[string]any{
	"Title": new(Title),
}
